### ISSUE TITLE
Specialized FITBIT DataExtraction script

### ISSUE THREAD

**Issue by hooman007** [ubcmist/ML#6]
make a customized python script that extracts requested data from Fitbit for certain days.
---

using the **ML\FITBIT_Data_Collection_Interface\DataExtraction.py**, make a custom script that takes arguments through the terminal when running the python code like bellow:

` python customDataExtract.py -t heart -d 20190111 -L address`
in which 
- ` -d ` or ` --date` is for the date given in the format above.
- `-t` or `--type` is for the data type, it can be `heart` or `sleep`  (sleep data extraction was not working yet)
- `-a` or '--address' is for the location to save the csv file.

**Requirements:**
- [ ] arguments should be for date, data type, and address of csv to be saved
- [ ] file name should have the date included
- [ ] make sure to check for the filename to see if it exist, meaning that data is already saved, so avoid requesting the data from server so we don't reach the hourly query limit. (check the DataExtraction.)

**Comment by hooman007** [comment]
just a guide on the argument query when running the python script, check the snippet bellow:

```
import os, argparse

parser = argparse.ArgumentParser(
    description='Trains VGG Teacher and Student Model.',
    epilog="For more information on arguments look at main.py")

parser.add_argument('-g', '--gpu', type=str, default="0", metavar='', help='Index of GPU to use (Default:0)')
parser.add_argument('-s', '--seed', type=int, default=123, metavar='', help='Seed value for random seed (Default:123)')
parser.add_argument('-d', '--dir', type=str, default='Model_Default', metavar='', help='Name of the folder to save the model (Default: Stanford_12View_SingleFrame_Seq_12x25)')
parser.add_argument('-t', '--teacher', type=str, default='Model_Default', metavar='', help='Name of the folder to save the model (Default: )')
parser.add_argument('-m', '--model', type=str, default='NONE', metavar='', help='Name of the model to train. Either vgg, dense, res')
args = vars(parser.parse_args())


os.environ["CUDA_VISIBLE_DEVICES"] = args['gpu']    
seed = args['seed']
FolderName = args['dir']
model_name = args['model']
```

**Comment by MasoudMokh** [comment]
I'll focus on this today.

**Comment by MasoudMokh** [comment]
What I did today:

Managed to write a test python script that can get arguments from the command line. I will integrate that with the program that reads data from Fitbit's .csv during the week.

**Comment by hooman007** [comment]
issues have been debugged. script is now ready and the README.md file contains the setup and usage instructions in https://github.com/ubcmist/ML/tree/master/FITBIT_Data_Collection_Interface
